server:
  port: 8888

spring:

  # 注册数据源
  datasource:
    # 指定数据源类型为Druid
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root
  # 配置缓存
  cache:
    # 指定缓存类型
    type: redis
    # 指定缓存区域名称
    cache-names: realTimeCache

  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456


  dubbo:
    application:
      name: provider
      registry: zookeeper://127.0.0.1:2181
    # zk集群作注册中心
    # registry: zookeeper://zkOS1:2181?backup=zkOS2:2181,zkOS3:2181


mybatis:
  # 注册mybatis中实体类的别名
  type-aliases-package: cn.eleven.bean
  # 注册映射文件
  mapper-locations: cn/eleven/provider/dao/*.xml